spring:
  application:
    name: italika-apirest
  datasource:
    username: postgres
    password: 1408
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/italika_database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
server:
  port: 8080
